

project:
  type: website

website:
  repo-url: https://github.com/simone-romiti/nested_sampling
  repo-actions: [edit, source, issue]
  navbar:
    left:
      - text: Project
        menu:
          - text: Overview
            href: index.qmd
          - text: "Nomenclature"
            href: nomenclature.qmd
          - text: "Structure of the project"
            href: structure_of_project.qmd
      - text: Theory
        menu:
          - text: "Nested Sampling"
            href: nested_sampling.qmd
  sidebar:
    - id: reference
      contents: "_sidebar.yml"

# citeproc: false
bibliography: biblio.bib
csl: physical-review-d.csl

execute:
  freeze: auto  # re-render only when source changes

title: "Lattice Data Tools: a set of libraries for the analysis of lattice data"
author: "Simone Romiti"
date: last-modified

format:
  html:
    theme: cosmo
    fontsize: 16pt
    embed-resources: true
    html-math-method: mathjax # use the common latex commands
    include-in-header: mathjax-config.html # equation numbering with sections
    toc-location: body
    code-fold: true
    code-summary: "Click to show the code block"
  pdf:
    documentclass: scrreprt

quartodoc:
  style: pkgdown
  dir: quartodoc_files
  package: null # quartodoc
  source_dir: ../
  sidebar: "_sidebar.yml"
  sections:
    - title: Model Averaging
      desc: Criteria for averaging different models
      contents:
        - artifacts


